name: Cleanup PR Resources
on:
  pull_request:
    types: [ closed ]
jobs:
  cleanup:
    runs-on: sonar-xs
    permissions:
      actions: write
    steps:
      - uses: SonarSource/ci-github-actions/pr_cleanup@d41706a4180f70b6c0d0479795309a6c99726022 # 2.0.0
